name: Rust

on:
  push:
    paths:
      - '.github/workflows/rust.yml'
      - 'src/**.rs'
      - '**.toml'
    branches:
      - master
  pull_request:
    paths:
      - '.github/workflows/rust.yml'
      - 'src/**.rs'
      - '**.toml'
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install Rust Unix
      if: runner.os != 'Windows'
      run: |
        if rustup --version >/dev/null 2>&1; then
            rustup update
        else
             curl https://sh.rustup.rs -sSf | sh -s -- -y --profile minimal --default-toolchain stable
             echo ::add-path::$HOME/.cargo/bin
        fi

    - name: Rust version
      run: |
        cargo --version
        rustc --version

    - name: Test
      run: cargo test
